server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sport_db?useSSL=false
    username: root
    password: root
  webflux:
    base-path: /api
  output:
    ansi:
      enabled: ALWAYS